### ISSUE TITLE
FireBase support

### ISSUE THREAD

**Issue by yashika51** [tokspace/tok-app#10]
Sorry if this is obvious but which file should support firebase thing? I am getting confused by the tutorials on youtube.
Should it be `src\index.js` or `src\login.js` ? @akainth015

**Comment by akainth015** [comment]
We will need to configure Firebase and import the submodules in `src\index.js`.
~~~jsx
import firebase from "firebase";
import "firebase/auth";

firebase.initalizeApp({...});
~~~
The `src\login.js` file would be able to use it with just `import firebase from "firebase"`
~~~jsx
firebase.auth().signInWithRedirect(...);
~~~
