### ISSUE TITLE
`firebase-authentication` branch breaks the app

### ISSUE THREAD

**Issue by yashika51** [tokspace/tok-app#19]
I have merged your recent changes @akainth015. Conflicts are resolved however the app is not working now. Can you see if there is really an issue or it's not working on just my machine?

![image](https://user-images.githubusercontent.com/34909206/87590655-c2c97280-c704-11ea-8292-6469bdc1f554.png)

**Comment by akainth015** [comment]
I think your account was in a bad state. I deleted it through the Firebase console, try recreating it.

**Comment by yashika51** [comment]
Now it gives me a blank window with no options. App works well on other branches though.

**Comment by akainth015** [comment]
It should work now

**Comment by yashika51** [comment]
Works 🎉
