### ISSUE TITLE
Explore Electron APIs for discovering other running applications on a user's machine

### ISSUE THREAD

**Issue by nchaloult** [tokspace/tok-app#6]
One of our app's primary planned features is being able to intelligently determine a user's "status," or "availability." In other social media or communication platforms, like Slack or Discord, users can manually set their current availability from a range of choices, including things like: "online", "away", "offline/do not disturb", etc. While our app's users have the option to manually set their status, they may also configure custom rules that tell the app when it should change their status automatically. One such example of this is that **if a user has VS Code open on their machine, their status should be set to "away/busy".** In order to implement functionality like this, our app needs to be able to observe which applications or processes are running on a user's machine.

So far, we've assumed that the Electron runtime offers APIs that make this possible, but haven't investigated. We need to figure out if Electron makes it possible to see what other programs users have running.

**Comment by akainth015** [comment]
I think we do not need Electron's APIs for this, Node should provide the appropriate capabilities.

**Comment by nchaloult** [comment]
> Node should provide the appropriate capabilities.

Mm, you're right. Looking into how to pass this information up from the main electron process to views 👍
